sonar.projectKey=owasp-benchmark
sonar.projectName=OWASP Benchmark
sonar.sources=data/benchmark/src/main/java/org/owasp/benchmark/testcode
sonar.java.binaries=data/benchmark/src/main/java/org/owasp/benchmark/testcode
sonar.host.url=http://localhost:9000
sonar.scm.disabled=true
